<?php
// Automatically Generated by TestLink Installer - Mon, 02 Sep 24 09:09:35 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '192.168.1.146');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
